export const recognitionConfig = {
  quality: {
    minBrightness: 45,
    maxBrightness: 225,
    minContrast: 22,
    minSharpness: 10,
    minResolution: 480,
  },
  detection: {
    sampleCropRatio: 0.85,
    searchWindowRatio: 0.48,
    searchStep: 12,
    normalizedSize: 1024,
    cropPaddingRatio: 0.18,
  },
  barcode: {
    formats: [
      'ean_13',
      'ean_8',
      'upc_a',
      'upc_e',
      'code_128',
      'code_39',
      'itf',
      'codabar',
    ],
  },
  scoring: {
    barcodeExactBoost: 0.42,
    barcodeHintBoost: 0.12,
    visualWeight: 0.24,
    roiHashWeight: 0.22,
    ocrTextWeight: 0.12,
    qualityPenaltyWeight: 0.18,
    confidentThreshold: 0.84,
    reviewThreshold: 0.64,
    rescanThreshold: 0.48,
    ambiguityMargin: 0.08,
  },
  roiRegions: [
    { id: 'title', x: 0.08, y: 0.08, width: 0.84, height: 0.22, weight: 1.15 },
    { id: 'variant', x: 0.12, y: 0.34, width: 0.76, height: 0.18, weight: 0.95 },
    { id: 'bottom', x: 0.1, y: 0.62, width: 0.8, height: 0.2, weight: 0.7 },
  ],
  diagnostics: {
    maxStoredRuns: 40,
  },
  aggregation: {
    bufferSize: 14,
    minAcceptedFrames: 4,
    maxFramesBeforeRescan: 18,
    frameIntervalMs: 350,
    decisionDebounceMs: 800,
    minQualityScore: 0.35,
    stableThreshold: 0.78,
    reviewThreshold: 0.62,
  },
  livePreview: {
    minBrightness: 52,
    maxBrightness: 222,
    minContrast: 18,
    minSharpness: 10.5,
    maxMotion: 0.042,
    minCoverage: 0.09,
    maxCoverage: 0.72,
    minCenteredness: 0.66,
    minAspectRatio: 0.38,
    requiredStableFrames: 8,
    burstFrames: 6,
    burstIntervalMs: 110,
    capturePadding: 0.08,
    targetRoi: {
      x: 0.31,
      y: 0.1,
      width: 0.38,
      height: 0.72,
    },
  },
} as const;

export type RecognitionConfig = typeof recognitionConfig;
